#
# Docker Compose for on playa operations
#
#
version: '3.7'

services:
  # API backend
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    image: apiserver:prod
    env_file: .rangers.env
    tty: true
    ports:
      - mode: host
        target: 80
        published: 8200
    volumes:
      - ./data/mugshots:/var/www/application/storage/mugshots
    depends_on:
      - db
    restart: unless-stopped

  # Clubhouse 2 frontend
  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    image: client:prod
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:8100:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # Classic Clubhouse
  classic:
    build:
      context: ./src/classic
      dockerfile: ./docker-playa/Dockerfile
    image: classic:prod
    env_file: .rangers.env
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:8300:80"
    depends_on:
      - db

  # Web server load balancer/frontend
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    image: nginx:prod
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/mugshots:/mugshots
    depends_on:
      - api
      - client

  #MySQL Service
  db:
    image: mysql:5.6
    env_file: .rangers.env
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:8306:3006"
    volumes:
      - ./data/mysql:/var/lib/mysql

  # SMTP Relay Server
  smtpd:
    build:
      context: ./services/smtpd
      dockerfile: Dockerfile
    image: smtpd:prod
    tty: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:8587:587"
      - "127.0.0.1:8025:25"
    env_file: .rangers.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      HOSTNAME: "ranger-clubhouse.nv.burningman.org"
      MASQUERADED_DOMAINS: "burningman.org"
      ALLOWED_SENDER_DOMAINS: "burningman.org"
      RELAYHOST: "[email-smtp.us-west-2.amazonaws.com]:587"

    volumes:
      - ./data/postfix:/var/spool/postfix
