#!/bin/bash

phones=/root/.monit-phones
config=/root/.twiliorc
twilio=/usr/local/bin/twilio

while getopts "c:p:e:" opt; do
	case "$opt" in
		c) config=$OPTARG ;;
		p) phones=$OPTARG ;;
    e) twilio=$OPTARG ;;
		*) echo "Unknown param: $opt"; exit ;;
	esac
done

if ! test -f ${phones}; then
  echo "${phones} does not exist."
  exit 1
fi

if ! test -f ${config}; then
  echo "${config} does not exist."
  exit 1
fi

if ! test -f ${twilio}; then
  echo "${twilio} does not exist."
  exit 1
fi

echo "$MONIT_SERVICE - $MONIT_EVENT @ $MONIT_DATE: $MONIT_DESCRIPTION" | ${twilio} -c ${config} $(cat ${phones})
